nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/site1/:/usr/share/nginx/html/site1/:rw
    - ./www/site2/:/usr/share/nginx/html/site2/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./logs/nginx/:/var/log/nginx/:rw
  links:
    # Links with php-fpm as an alias "fpm",
    # Nginx should config fpm:<port> to work with php-fpm
    - php-fpm:fpm

php-fpm:
  build: ./
  ports:
    # Expose 9000 port to linked services, here is nginx
    - "9000"
  volumes:
    - ./www/site1/:/usr/share/nginx/html/site1/:rw
    - ./www/site2/:/usr/share/nginx/html/site2/:rw
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php/conf.d:/usr/local/etc/php/conf.d/:ro
    - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
    - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    - ./logs/php-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql

mysql:
  image: mysql:latest
  ports:
    # Expose 3306 port to host
    - "3306:3306"
  volumes:
    - ./mysql/:/var/lib/mysql/
    - ./logs/mysql/:/var/log/mysql/
  environment:
    # MYSQL root password, you should change for your application
    MYSQL_ROOT_PASSWORD: "123456"
